name: Upload Widget Dependencies Package
on: push
jobs:
  checkout-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12.3.1'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@clpetersonucf'
      - run: yarn install
      - run: yarn build
      - run: yarn publish
        working-directory: ./public/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}